### ISSUE TITLE
i want to run yolo object detection in valkka mvision

### ISSUE THREAD

**Issue by deepik27** [elsampsa/valkka-live#11]
1) When i ran the python3 base.py N file i got this error (attached the error), what i should do to run yolo object detection using rtsp link, can you please guide me the steps to run the yolo object detection using valkka vision

bng-6@bng-6:~/MoniDeepika/Monideepika/valkka_live_camera/valkka-live/valkka/mvision/movement$ python3 base.py N
Traceback (most recent call last):
  File "base.py", line 20, in <module>
    from valkka.live.qimport import QtWidgets, QtCore, QtGui, Signal, Slot
  File "/home/bng-6/lib/python3.8/site-packages/valkka_live-1.0.1-py3.8.egg/valkka/live/__init__.py", line 1, in <module>
    from valkka.live.version import version_tag
  File "/home/bng-6/lib/python3.8/site-packages/valkka_live-1.0.1-py3.8.egg/valkka/live/version.py", line 23, in <module>
    from valkka.core import VERSION_MAJOR as VALKKA_VERSION_MAJOR
ModuleNotFoundError: No module named 'valkka.core'

2) I am not finding proper steps to execute mvision for yolo objection in valkka please can you guide me the steps

**Comment by elsampsa** [comment]
That error means you have not installed libValkka.  Please remember to run the script "install-valkka-core" as mentioned in valkka live repo front page.  Or alternatively, follow these instructions:  https://elsampsa.github.io/valkka-examples/_build/html/requirements.html
