### ISSUE TITLE
Linux Mint / Ubuntu jammy  PySide2==5.14.2 missing

### ISSUE THREAD

**Issue by jenswes** [elsampsa/valkka-live#12]
Yes, i can confirm this:
 # python packaging is in a state of mess, as usual

Hello,
i just want to give it a try, i'm on Linux Mint vera (ubuntu jammy)

PySide2==5.14.2 (from valkka-live) (from versions:.....5.13.2, 5.15.2.1)

however - here they leave out the 5.14.x versions

using the older one  5.13.2 doesn't help
The conflict is caused by:
    valkka-live 1.1.0 depends on PySide2>=5.13.2
    cute-mongo-forms 0.7.3 depends on PySide2==5.14.2

Here is it:
https://pypi.org/project/PySide2/5.14.2/#files

but how to use?

thanks for any help

wespe

**Comment by elsampsa** [comment]
The PySide2 version is now "relaxed" both in cute_mongo_forms and valkka_live.
