### ISSUE TITLE
Valkka-live installation issues.

### ISSUE THREAD

**Issue by marek0039** [elsampsa/valkka-live#3]
Hello I am trying to install Valkka-live on my ubuntu machine. I am following all the steps on https://elsampsa.github.io/valkka-live/_build/html/index.html . It is running on Ubuntu 18.04, python 3.6.7 and pip 19.1.1. this is the error message when I try to run valkka-live
```
valkka.mvision.__init__ : could not import module movement : 'No module named 'cv2''
valkka.mvision.__init__ : could not import module alpr : 'No module named 'cv2''
valkka.mvision.__init__ : could not import module nix : 'No module named 'cv2''
valkka.mvision.__init__ : could not import module yolo3 : 'No module named 'darknet''
valkka.mvision.__init__ : could not import module yolo2 : 'No module named 'darknet''
valkka.mvision.__init__ : could not import module yolo3tiny : 'No module named 'darknet''
mvision scan: submodule valkka.mvision.base missing MVisionProcess
mvision scan: submodule valkka.mvision.multiprocess missing MVisionProcess
valkka.live : initConfigFiles : first start
valkka.live : save_window_layout : container_dic = {'container_list': [], 'mvision_container_list': []}
valkka.live : readDB : first start
DeviceList :  clearSelection
QCheckBoxColumn: state_changed_slot : live_main
SlotFormSet :  showCurrent: current_row= None
QCheckBoxColumn: state_changed_slot : bind
MemoryConfigForm :  no row!
CPUScheme : cores 16
valkka.live : Using default mem config
CPUScheme : cores 16
GPUHandler: findXScreens: true screens: [<PySide2.QtGui.QScreen object at 0x7feb530ff408>]
gpuhandler : GPUHandler: starting OpenGLThread with :0.0
Invalid MIT-MAGIC-COOKIE-1 keyOpenGLThtead: initGLX: cannot connect to X server :0.0
QObject::~QObject: Timers cannot be stopped from another thread
```
here is my ```$DISPLAY```:
```
marekn@Bizon-DevBOX:~$ echo $DISPLAY
:2
```

**Comment by elsampsa** [comment]
Hi,

- Those first "error" messages ```could not import module```, are not really errors.  It just informs you that some modules (for machine vision) are missing
- This error message is for real:
```
OpenGLThtead: initGLX: cannot connect to X server :0.0
```
- It's because Valkka uses by default X screen ```:0.0```

Why is your X screen ```:0.2``` ?  Are you trying to do multi-gpu / multi-xscreen stuff?

**Comment by elsampsa** [comment]
A quick & dirty hack, if you only have one X screen:
In Valkka Live source code, look at the file ```gpuhandler.py```, and there, search for the line:
```
x_connection = ":0." + str(n_gpu)
```
Substitute it with:
```
x_connection = ":0." + str(n_gpu+2)
```
However, if you're doing some multi-gpu / multi-xscreen system, then it seems that Valkka Live can't figure out the correct first X Screen (which in your case is ```:0.2```).

**Comment by marek0039** [comment]
We got it working thank you.

**Comment by elsampsa** [comment]
@marek0039, someone has a similar issue.  Maybe you could of assistance..?   Please see here: https://github.com/elsampsa/valkka-live/issues/6
